import Link from "next/link";
import LineCta from "@/components/LineCta";
import { metadataForPath } from "@/lib/seo-config";
import { loadSeoState } from "@/lib/seo-store";
import { siteImages } from "@/lib/site-images";

export async function generateMetadata(){const seo=await loadSeoState();return metadataForPath("/destinations",seo.pages)}

const cities=[
  {id:"paro",en:"Paro",th:"พาโร",desc:"ประตูสู่ภูฏานและเมืองที่หลายคนตกหลุมรักตั้งแต่วันแรก ทั้งหุบเขา วัดเก่า และวัดทักซังบนหน้าผา",places:"Tiger’s Nest · Paro Dzong · National Museum",image:siteImages.tigerNest,mood:"เหมาะกับครั้งแรกที่ไปภูฏาน",best:["วัดทักซังบนหน้าผา","เมืองเก่าบรรยากาศสงบ","ใกล้สนามบิน เดินทางสะดวก"]},
  {id:"thimphu",en:"Thimphu",th:"ทิมพู",desc:"เมืองหลวงที่รวมสถาปัตยกรรมดั้งเดิม ชีวิตร่วมสมัย และสถานที่สำคัญของประเทศไว้ในเมืองเดียว",places:"Tashichho Dzong · Memorial Chorten · Buddha Point",image:siteImages.thimphuDzong,mood:"เหมาะกับคนที่ชอบเมืองและวัฒนธรรม",best:["เห็นจังหวะชีวิตของภูฏาน","แลนด์มาร์กสำคัญอยู่ใกล้กัน","ร้านกาแฟและงานฝีมือท้องถิ่น"]},
  {id:"punakha",en:"Punakha",th:"พูนาคา",desc:"อดีตเมืองหลวงในหุบเขาอากาศอบอุ่น โดดเด่นด้วย Punakha Dzong ที่ตั้งอยู่บริเวณจุดบรรจบของแม่น้ำสองสาย",places:"Punakha Dzong · Dochula Pass · Chimi Lhakhang",image:siteImages.punakhaDzong,mood:"เหมาะกับคนที่อยากได้วิวสวยและรูปสวย",best:["วิวป้อมริมแม่น้ำโดดเด่น","บรรยากาศอบอุ่นกว่าเมืองสูง","ต่อเส้นทางจากโดชูลาพาสได้ลงตัว"]},
  {id:"gangtey",en:"Gangtey / Phobjikha",th:"กังเต / โฟบจิกา",desc:"พื้นที่หุบเขาธรรมชาติที่สงบกว่าทริปเมืองหลัก เหมาะสำหรับคนที่อยากเห็นอีกมุมของภูฏานและเพิ่มเวลาสัมผัสธรรมชาติ",places:"Phobjikha Valley · Gangtey Goenpa · Nature Trail",image:siteImages.phobjikhaValley,mood:"เหมาะกับคนที่อยากได้ภูฏานแบบสงบและธรรมชาติ",best:["หุบเขากว้างสบายตา","บรรยากาศเงียบและผ่อนคลาย","เหมาะกับทริป 6 วันขึ้นไป"]},
];

export default function DestinationsPage(){return <>
  <section className="inner-hero destination-sales-hero"><div className="page-container inner-hero-grid"><div><span className="section-label">DISCOVER BHUTAN</span><h1>แต่ละเมือง<br/><em>ให้ความรู้สึกไม่เหมือนกัน</em></h1></div><div className="inner-hero__copy"><p>ดูภาพจริงและไฮไลต์ของแต่ละพื้นที่ก่อนเลือกแพ็กเกจ เพื่อให้รู้ว่าควรใช้เวลา 4, 5 หรือ 6 วันจึงจะพอดีกับสิ่งที่อยากเห็น</p><Link href="/packages" className="gold-button">เทียบแพ็กเกจ 4–6 วัน <span>↗</span></Link></div></div></section>
  <section className="section destination-overview-section"><div className="page-container"><div className="section-intro"><span className="eyebrow">DESTINATION OVERVIEW</span><h2>เลือกอารมณ์ของทริป<br/>ก่อนค่อยเลือกจำนวนวัน</h2><p>แต่ละพื้นที่ของภูฏานให้อารมณ์ต่างกันชัดเจน บางเมืองเหมาะกับคนที่อยากเห็นวัดบนหน้าผา บางเมืองเหมาะกับวิวริมแม่น้ำ หรือคนที่อยากได้ธรรมชาติสงบ ๆ</p></div><div className="destination-glance-grid">{cities.map((city)=><a key={city.id} href={`#${city.id}`} className="destination-glance-card"><img src={city.image} alt={`${city.en}, Bhutan`} /><div><small>{city.en.toUpperCase()}</small><strong>{city.th}</strong><p>{city.mood}</p></div></a>)}</div></div></section><section className="section"><div className="page-container destination-editorial-list">{cities.map((city,index)=><article id={city.id} className="destination-editorial" key={city.en}><div className="destination-editorial-media"><img src={city.image} alt={`${city.en}, Bhutan`}/><span>0{index+1}</span><div className="destination-photo-label"><small>{city.en.toUpperCase()}</small><strong>{city.places.split(" · ")[0]}</strong></div></div><div className="destination-editorial-copy"><small>{city.en.toUpperCase()}</small><h2>{city.th}</h2><p>{city.desc}</p><div className="destination-mood-badge">{city.mood}</div><strong>{city.places}</strong><ul className="destination-bullet-list">{city.best.map((item)=><li key={item}>{item}</li>)}</ul><div className="destination-actions"><Link href="/packages" className="text-link">ดูแพ็กเกจที่เหมาะ <span>→</span></Link><LineCta className="destination-line-link">ถามทีมเรื่องเมืองนี้ทาง LINE</LineCta></div></div></article>)}</div></section>
  <section className="section destination-final-cta"><div className="page-container callout"><div><h2>อยากไปหลายเมือง แต่ไม่รู้กี่วันดี?</h2><p>ส่งรายชื่อเมืองหรือสถานที่ที่อยากไป ทีมจะช่วยจัดจำนวนวันและลำดับเส้นทางให้เหมาะกับเวลาจริง</p></div><LineCta className="button button--gold">ให้ทีมช่วยจัดเส้นทาง <span>→</span></LineCta></div></section>
</>}
